<?php

/**
 * Delegated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Delegated extends BaseDelegated
{

    public function  getMessage() {
        return "delegated";
    }

    public function getDiscriminator(){
        return "DELEGATED";
    }
}
