<?php

/**
 * DoASAP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class DoASAP extends BaseDoASAP
{

    public function  getMessage() {
        return "do_as_soon_as_i_can";
    }
    public function getDiscriminator(){
        return "DO_ASAP";
    }
}
