<?php

/**
 * EmailItemAlertConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class EmailItemAlertConfiguration extends BaseEmailItemAlertConfiguration
{
  public function getDiscriminator() {
    return 'EMAIL_ITEM';
  }
}
