<?php

/**
 * Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Project extends BaseProject
{
  public function getNextActions(){
    $actions = new Doctrine_Collection('NextAction');
    foreach ($this->getProjectActions() as $rel) {
      $actions->add($rel->getNextAction());
    }
    return $actions;
  }
}
