<?php

/**
 * Scheduled
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Scheduled extends BaseScheduled
{
    public function  getMessage() {
        return "put_into_my_calendar";
    }
    public function getDiscriminator(){
        return "SCHEDULED";
    }
}
