<?php

/**
 * BaseProjectState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $type
 * @property Doctrine_Collection $StateProjects
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method varchar             getType()          Returns the current record's "type" value
 * @method Doctrine_Collection getStateProjects() Returns the current record's "StateProjects" collection
 * @method ProjectState        setId()            Sets the current record's "id" value
 * @method ProjectState        setType()          Sets the current record's "type" value
 * @method ProjectState        setStateProjects() Sets the current record's "StateProjects" collection
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProjectState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_state');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('type', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '50',
             ));

        $this->setSubClasses(array(
             'ActualProject' => 
             array(
              'type' => 'ACTUAL_PROJECT',
             ),
             'CompletedProject' => 
             array(
              'type' => 'COMPLETED_PROJECT',
             ),
             'FutureProject' => 
             array(
              'type' => 'FUTURE_PROJECT',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as StateProjects', array(
             'local' => 'id',
             'foreign' => 'project_state_id'));
    }
}