<?php

/**
 * BaseProjectAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $value
 * @property integer $project_id
 * @property Project $Project
 * 
 * @method integer           getId()         Returns the current record's "id" value
 * @method varchar           getValue()      Returns the current record's "value" value
 * @method integer           getProjectId()  Returns the current record's "project_id" value
 * @method Project           getProject()    Returns the current record's "Project" value
 * @method ProjectAttachment setId()         Sets the current record's "id" value
 * @method ProjectAttachment setValue()      Sets the current record's "value" value
 * @method ProjectAttachment setProjectId()  Sets the current record's "project_id" value
 * @method ProjectAttachment setProject()    Sets the current record's "Project" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProjectAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_attachment');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('value', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('project_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'value',
             ),
             'name' => 'normalized_value',
             'type' => 'string',
             'length' => 255,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}