<?php

/**
 * BaseAlertConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $value
 * @property varchar $type
 * @property integer $user_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method varchar            getValue()       Returns the current record's "value" value
 * @method varchar            getType()        Returns the current record's "type" value
 * @method integer            getUserId()      Returns the current record's "user_id" value
 * @method sfGuardUser        getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AlertConfiguration setId()          Sets the current record's "id" value
 * @method AlertConfiguration setValue()       Sets the current record's "value" value
 * @method AlertConfiguration setType()        Sets the current record's "type" value
 * @method AlertConfiguration setUserId()      Sets the current record's "user_id" value
 * @method AlertConfiguration setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAlertConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alert_configuration');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('value', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('type', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));

        $this->setSubClasses(array(
             'EmailItemAlertConfiguration' => 
             array(
              'type' => 'EMAIL_ITEM',
             ),
             'ScheludedItemAlertConfiguration' => 
             array(
              'type' => 'SCHELUDED_ITEM',
             ),
             'DelegateItemAlertConfiguration' => 
             array(
              'type' => 'DELEGATE_ITEM',
             ),
             'DoAsapItemAlertConfiguration' => 
             array(
              'type' => 'DO_ASAP_ITEM',
             ),
             'SomeDayMaybeItemAlertConfiguration' => 
             array(
              'type' => 'SOME_DAY_MAYBE_ITEM',
             ),
             'DayScheludedItemAlertConfiguration' => 
             array(
              'type' => 'DAY_SCHELUDED_ITEM',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}