<?php

/**
 * BaseBookmark
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $item_id
 * @property integer $user_id
 * @property varchar $value
 * @property varchar $type
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method varchar     getItemId()      Returns the current record's "item_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method varchar     getValue()       Returns the current record's "value" value
 * @method varchar     getType()        Returns the current record's "type" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Bookmark    setId()          Sets the current record's "id" value
 * @method Bookmark    setItemId()      Sets the current record's "item_id" value
 * @method Bookmark    setUserId()      Sets the current record's "user_id" value
 * @method Bookmark    setValue()       Sets the current record's "value" value
 * @method Bookmark    setType()        Sets the current record's "type" value
 * @method Bookmark    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBookmark extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bookmark');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('item_id', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('value', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('type', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));

        $this->setSubClasses(array(
             'ProjectsMark' => 
             array(
              'type' => 'PROJECTS_MARK',
             ),
             'NextActionsMark' => 
             array(
              'type' => 'NEXT_ACTIONS_MARK',
             ),
             'StuffsMark' => 
             array(
              'type' => 'STUFFS_MARK',
             ),
             'SomeDaysMark' => 
             array(
              'type' => 'SOME_DAYS_MARK',
             ),
             'ReferencesMark' => 
             array(
              'type' => 'REFERENCES_MARK',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}