<?php

/**
 * BaseNextActionCriteria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $next_action_id
 * @property integer $criteria_id
 * @property NextAction $NextAction
 * @property Criteria $Criteria
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getNextActionId()   Returns the current record's "next_action_id" value
 * @method integer            getCriteriaId()     Returns the current record's "criteria_id" value
 * @method NextAction         getNextAction()     Returns the current record's "NextAction" value
 * @method Criteria           getCriteria()       Returns the current record's "Criteria" value
 * @method NextActionCriteria setId()             Sets the current record's "id" value
 * @method NextActionCriteria setNextActionId()   Sets the current record's "next_action_id" value
 * @method NextActionCriteria setCriteriaId()     Sets the current record's "criteria_id" value
 * @method NextActionCriteria setNextAction()     Sets the current record's "NextAction" value
 * @method NextActionCriteria setCriteria()       Sets the current record's "Criteria" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNextActionCriteria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('next_action_criteria');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('next_action_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('criteria_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NextAction', array(
             'local' => 'next_action_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Criteria', array(
             'local' => 'criteria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}