<?php

/**
 * BaseProjectsMark
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProjectsMark extends Bookmark
{
    public function setUp()
    {
        parent::setUp();
        
    }
}