<?php

/**
 * BaseNextActionInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $next_action_id
 * @property string $value
 * @property varchar $type
 * @property NextAction $NextAction
 * 
 * @method integer        getNextActionId()   Returns the current record's "next_action_id" value
 * @method string         getValue()          Returns the current record's "value" value
 * @method varchar        getType()           Returns the current record's "type" value
 * @method NextAction     getNextAction()     Returns the current record's "NextAction" value
 * @method NextActionInfo setNextActionId()   Sets the current record's "next_action_id" value
 * @method NextActionInfo setValue()          Sets the current record's "value" value
 * @method NextActionInfo setType()           Sets the current record's "type" value
 * @method NextActionInfo setNextAction()     Sets the current record's "NextAction" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNextActionInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('next_action_info');
        $this->hasColumn('next_action_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('value', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('type', 'varchar', 30, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '30',
             ));

        $this->setSubClasses(array(
             'DueDate' => 
             array(
              'type' => 'DUE_DATE',
             ),
             'DelegatedTo' => 
             array(
              'type' => 'DELEGATED_TO',
             ),
             'FollowUpDate' => 
             array(
              'type' => 'FOLLOW_UP_DATE',
             ),
             'FollowUpTime' => 
             array(
              'type' => 'FOLLOW_UP_TIME',
             ),
             'ToDoInDateStart' => 
             array(
              'type' => 'TO_DO_IN_DATE_START',
             ),
             'ToDoInDateEnd' => 
             array(
              'type' => 'TO_DO_IN_DATE_END',
             ),
             'ToDoInHourStart' => 
             array(
              'type' => 'TO_DO_IN_HOUR_START',
             ),
             'ToDoInHourEnd' => 
             array(
              'type' => 'TO_DO_IN_HOUR_END',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NextAction', array(
             'local' => 'next_action_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}