<?php

/**
 * BaseCriteria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $value
 * @property string $unit
 * @property string $type
 * @property integer $user_id
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $CriteriaNextActions
 * 
 * @method string              getValue()               Returns the current record's "value" value
 * @method string              getUnit()                Returns the current record's "unit" value
 * @method string              getType()                Returns the current record's "type" value
 * @method integer             getUserId()              Returns the current record's "user_id" value
 * @method sfGuardUser         getSfGuardUser()         Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getCriteriaNextActions() Returns the current record's "CriteriaNextActions" collection
 * @method Criteria            setValue()               Sets the current record's "value" value
 * @method Criteria            setUnit()                Sets the current record's "unit" value
 * @method Criteria            setType()                Sets the current record's "type" value
 * @method Criteria            setUserId()              Sets the current record's "user_id" value
 * @method Criteria            setSfGuardUser()         Sets the current record's "sfGuardUser" value
 * @method Criteria            setCriteriaNextActions() Sets the current record's "CriteriaNextActions" collection
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCriteria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('criteria');
        $this->hasColumn('value', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('unit', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '50',
             ));
        $this->hasColumn('type', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));

        $this->setSubClasses(array(
             'Context' => 
             array(
              'type' => 'CONTEXT',
             ),
             'Energy' => 
             array(
              'type' => 'ENERGY',
             ),
             'TimeAvailable' => 
             array(
              'type' => 'TIME_AVAILABLE',
             ),
             'Priority' => 
             array(
              'type' => 'PRIORITY',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('NextActionCriteria as CriteriaNextActions', array(
             'local' => 'id',
             'foreign' => 'criteria_id'));
    }
}