<?php

/**
 * BaseNextActionProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $next_action_id
 * @property NextAction $NextAction
 * @property Project $Project
 * 
 * @method integer           getNextActionId()   Returns the current record's "next_action_id" value
 * @method NextAction        getNextAction()     Returns the current record's "NextAction" value
 * @method Project           getProject()        Returns the current record's "Project" value
 * @method NextActionProject setNextActionId()   Sets the current record's "next_action_id" value
 * @method NextActionProject setNextAction()     Sets the current record's "NextAction" value
 * @method NextActionProject setProject()        Sets the current record's "Project" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNextActionProject extends ActionProject
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('next_action_project');
        $this->hasColumn('next_action_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NextAction', array(
             'local' => 'next_action_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}