<?php

/**
 * BaseStuffAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $value
 * @property integer $stuff_id
 * @property Stuff $Stuff
 * 
 * @method integer         getId()       Returns the current record's "id" value
 * @method varchar         getValue()    Returns the current record's "value" value
 * @method integer         getStuffId()  Returns the current record's "stuff_id" value
 * @method Stuff           getStuff()    Returns the current record's "Stuff" value
 * @method StuffAttachment setId()       Sets the current record's "id" value
 * @method StuffAttachment setValue()    Sets the current record's "value" value
 * @method StuffAttachment setStuffId()  Sets the current record's "stuff_id" value
 * @method StuffAttachment setStuff()    Sets the current record's "Stuff" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseStuffAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stuff_attachment');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('value', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('stuff_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stuff', array(
             'local' => 'stuff_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'value',
             ),
             'name' => 'normalized_value',
             'type' => 'string',
             'length' => 255,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}