<?php

/**
 * BaseNextActionStuff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stuff_id
 * @property integer $next_action_id
 * @property NextAction $NextAction
 * @property Stuff $Stuff
 * 
 * @method integer         getStuffId()        Returns the current record's "stuff_id" value
 * @method integer         getNextActionId()   Returns the current record's "next_action_id" value
 * @method NextAction      getNextAction()     Returns the current record's "NextAction" value
 * @method Stuff           getStuff()          Returns the current record's "Stuff" value
 * @method NextActionStuff setStuffId()        Sets the current record's "stuff_id" value
 * @method NextActionStuff setNextActionId()   Sets the current record's "next_action_id" value
 * @method NextActionStuff setNextAction()     Sets the current record's "NextAction" value
 * @method NextActionStuff setStuff()          Sets the current record's "Stuff" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNextActionStuff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('next_action_stuff');
        $this->hasColumn('stuff_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('next_action_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NextAction', array(
             'local' => 'next_action_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Stuff', array(
             'local' => 'stuff_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}