<?php

/**
 * BaseStuff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property text $description
 * @property integer $user_id
 * @property integer $stuff_state_id
 * @property sfGuardUser $sfGuardUser
 * @property StuffState $StuffState
 * @property Doctrine_Collection $StuffAttachments
 * @property Doctrine_Collection $RelatedNextActions
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method varchar             getName()               Returns the current record's "name" value
 * @method text                getDescription()        Returns the current record's "description" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method integer             getStuffStateId()       Returns the current record's "stuff_state_id" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method StuffState          getStuffState()         Returns the current record's "StuffState" value
 * @method Doctrine_Collection getStuffAttachments()   Returns the current record's "StuffAttachments" collection
 * @method Doctrine_Collection getRelatedNextActions() Returns the current record's "RelatedNextActions" collection
 * @method Stuff               setId()                 Sets the current record's "id" value
 * @method Stuff               setName()               Sets the current record's "name" value
 * @method Stuff               setDescription()        Sets the current record's "description" value
 * @method Stuff               setUserId()             Sets the current record's "user_id" value
 * @method Stuff               setStuffStateId()       Sets the current record's "stuff_state_id" value
 * @method Stuff               setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method Stuff               setStuffState()         Sets the current record's "StuffState" value
 * @method Stuff               setStuffAttachments()   Sets the current record's "StuffAttachments" collection
 * @method Stuff               setRelatedNextActions() Sets the current record's "RelatedNextActions" collection
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseStuff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stuff');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('stuff_state_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('StuffState', array(
             'local' => 'stuff_state_id',
             'foreign' => 'id'));

        $this->hasMany('StuffAttachment as StuffAttachments', array(
             'local' => 'id',
             'foreign' => 'stuff_id'));

        $this->hasMany('NextActionStuff as RelatedNextActions', array(
             'local' => 'id',
             'foreign' => 'stuff_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'name',
             ),
             'name' => 'normalized_name',
             'type' => 'string',
             'length' => 255,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}