<?php

/**
 * BaseInviteAfriend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property varchar $email
 * @property string $hash
 * @property integer $status
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getUserId()      Returns the current record's "user_id" value
 * @method varchar       getEmail()       Returns the current record's "email" value
 * @method string        getHash()        Returns the current record's "hash" value
 * @method integer       getStatus()      Returns the current record's "status" value
 * @method sfGuardUser   getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method InviteAfriend setId()          Sets the current record's "id" value
 * @method InviteAfriend setUserId()      Sets the current record's "user_id" value
 * @method InviteAfriend setEmail()       Sets the current record's "email" value
 * @method InviteAfriend setHash()        Sets the current record's "hash" value
 * @method InviteAfriend setStatus()      Sets the current record's "status" value
 * @method InviteAfriend setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInviteAfriend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invite_a_friend');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('email', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('hash', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}