<?php

/**
 * BaseNextActionState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property varchar $type
 * @property Doctrine_Collection $NextActions
 * 
 * @method varchar             getName()        Returns the current record's "name" value
 * @method varchar             getType()        Returns the current record's "type" value
 * @method Doctrine_Collection getNextActions() Returns the current record's "NextActions" collection
 * @method NextActionState     setName()        Sets the current record's "name" value
 * @method NextActionState     setType()        Sets the current record's "type" value
 * @method NextActionState     setNextActions() Sets the current record's "NextActions" collection
 * 
 * @package    EasyGtd
 * @subpackage model
 * @author     leobarrientosc
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNextActionState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('next_action_state');
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('type', 'varchar', 30, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '30',
             ));

        $this->setSubClasses(array(
             'ToDo' => 
             array(
              'type' => 'TO_DO',
             ),
             'Done' => 
             array(
              'type' => 'DONE',
             ),
             'Notificated' => 
             array(
              'type' => 'NOTIFICATED',
             ),
             'Delivered' => 
             array(
              'type' => 'DELIVERED',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NextAction as NextActions', array(
             'local' => 'id',
             'foreign' => 'next_action_state_id'));
    }
}