# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: realtime
      transport:
      class: Swift_SmtpTransport
      param:
        host:       mail3.opensistemas.com
        port:       25
        encryption: TLS
        username:   prueba1
        password:   .prueba1.

dev:
  mailer:
    param:
      delivery_strategy: realtime
      transport:
      class: Swift_SmtpTransport
      param:
        host:       mail3.opensistemas.com
        port:       25
        encryption: TLS
        username:   prueba1@opensistemas.com
        password:   .prueba1.

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
  
  user:
    class: sfGuardSecurityUser
    param:
      timeout: 31557600    
  
