# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true
    web_debug:              false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         true
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            ed2ea53f277d862e1352e35e0e17c30c9b7bc467

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    
    enabled_modules:        [default, sfDoctrineTree, sfGuardAuth]

    # Enable the database manager
    use_database:           true

    standard_helpers:       [Lightbox, Partial, Date, Pagination, I18N, Cache, Javascript]
    i18n:                   on       # Enable interface translation. Set to off if your application should not be translated.

  .actions:
    login_module:           sfGuardAuth
    login_action:           signin
    
    secure_module:          sfGuardAuth
    secure_action:          secure
