startSuccess:
  stylesheets:    [app/jquery.fancybox-1.3.1.css,app/jquery_theme/jquery-ui-1.8.2.custom.css]
  javascripts:    [jquery/jquery.form.js,app/jquery/jquery.validate.js,app/jquery/jquery.metadata.js,app/jquery.fancybox-1.3.1.js,jquery/jquery.ui.widget.js,jquery/jquery-ui-1.8.2.custom.js,jquery/jquery.ui.dialog.js,app/attachment.js,jquery/jquery-ui-timepicker-addon.js]

edit_actionSuccess:
  stylesheets:    [app/jquery.fancybox-1.3.1.css,app/jquery_theme/jquery-ui-1.8.2.custom.css]
  javascripts:    [jquery/jquery.form.js,app/jquery/jquery.validate.js,app/jquery/jquery.metadata.js,app/jquery.fancybox-1.3.1.js,jquery/jquery.ui.widget.js,jquery/jquery-ui-1.8.2.custom.js,jquery/jquery.ui.dialog.js,app/attachment.js,jquery/jquery-ui-timepicker-addon.js]
